airflow_dbt_snowflake:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('WAREHOUSE_HOST', 'analytics-db') }}"
      port: "{{ env_var('WAREHOUSE_PORT', '5432') | int }}"
      user: "{{ env_var('WAREHOUSE_USER', 'game') }}"
      password: "{{ env_var('WAREHOUSE_PASSWORD', 'gamepass') }}"
      dbname: "{{ env_var('WAREHOUSE_DB', 'game_warehouse') }}"
      schema: "{{ env_var('WAREHOUSE_SCHEMA', 'public') }}"
      threads: 4
